import { Category } from "./types";

export const categoriesData: Category[] = [
  // Brands (left column)
  {
    id: "apple",
    name: "Apple",
    slug: "apple",
    type: "brand",
    subcategories: [
      "iPhone",
      "Apple Watch",
      "Air Pods",
      "iMac",
      "iPad",
      "MacBook",
      "Mac mini",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "xiaomi",
    name: "Xiaomi",
    slug: "xiaomi",
    type: "brand",
    subcategories: [
      "Смартфоны",
      "Умные часы",
      "Наушники",
      "Планшеты",
      "Ноутбуки",
      "Умный дом",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "smartphones",
    name: "Смартфоны",
    slug: "smartphones",
    type: "category",
    subcategories: [
      "iPhone",
      "Samsung",
      "Xiaomi",
      "Google Pixel",
      "OnePlus",
      "Realme",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "smart-watches",
    name: "Умные часы",
    slug: "smart-watches",
    type: "category",
    subcategories: [
      "Apple Watch",
      "Samsung Galaxy Watch",
      "Xiaomi Watch",
      "Garmin",
      "Huawei Watch",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "accessories",
    name: "Аксессуары",
    slug: "accessories",
    type: "category",
    subcategories: [
      "Чехлы",
      "Зарядки",
      "Кабели",
      "Power Bank",
      "Защитные стёкла",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  // Categories (right column)
  {
    id: "samsung",
    name: "Samsung",
    slug: "samsung",
    type: "brand",
    subcategories: [
      "Galaxy S",
      "Galaxy Z",
      "Galaxy Watch",
      "Galaxy Buds",
      "Galaxy Tab",
      "Galaxy Book",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "dyson",
    name: "Dyson",
    slug: "dyson",
    type: "brand",
    subcategories: [
      "Пылесосы",
      "Фены",
      "Стайлеры",
      "Очистители воздуха",
      "Вентиляторы",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "laptops",
    name: "Ноутбуки",
    slug: "laptops",
    type: "category",
    subcategories: ["MacBook", "Windows", "Gaming", "Для работы", "Для учёбы"],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "headphones",
    name: "Наушники",
    slug: "headphones",
    type: "category",
    subcategories: [
      "AirPods",
      "Sony",
      "Samsung",
      "JBL",
      "Beats",
      "Накладные",
      "Вкладыши",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
  {
    id: "gaming",
    name: "Игровые приставки",
    slug: "gaming",
    type: "category",
    subcategories: [
      "PlayStation 5",
      "Xbox",
      "Nintendo Switch",
      "Игры",
      "Геймпады",
    ],
    description: "Новые устройства с гарантией лучшей цены!",
  },
];
