import { Product, ProductDetail } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Беспроводные наушники Apple AirPods Max Space Gray (MGYH3)",
    price: 40990,
    images: [
      "/images/headphones.png",
      "/images/headphones.png",
      "/images/headphones.png",
    ],
    inStock: true,
    isNew: true,
  },
  {
    id: "2",
    title: "Беспроводные наушники Apple AirPods Max Space Gray (MGYH3)",
    price: 40990,
    images: ["/images/headphones.png", "/images/headphones.png"],
    inStock: true,
    isNew: true,
  },
  {
    id: "3",
    title: "Беспроводные наушники Apple AirPods Max Space Gray (MGYH3)",
    price: 40990,
    images: ["/images/headphones.png"],
    inStock: true,
    isNew: true,
  },
  {
    id: "4",
    title: "Беспроводные наушники Apple AirPods Max Space Gray (MGYH3)",
    price: 40990,
    images: ["/images/headphones.png"],
    inStock: true,
    isNew: true,
  },
];

export const mockRelatedProducts: Product[] = [
  {
    id: "related-1",
    title: "Смартфон Apple iPhone 17 Pro Max 256Gb Cosmic Blue",
    price: 149990,
    images: ["/images/phone_mock.png", "/images/phone_mock.png"],
    inStock: true,
  },
  {
    id: "related-2",
    title: "Смартфон Apple iPhone 17 Pro 256Gb Natural Titanium",
    price: 119990,
    images: ["/images/phone_mock.png", "/images/phone_mock.png"],
    inStock: true,
  },
  {
    id: "related-3",
    title: "Смартфон Apple iPhone 17 128Gb Black",
    price: 89990,
    images: ["/images/phone_mock.png", "/images/phone_mock.png"],
    inStock: true,
  },
  {
    id: "related-4",
    title: "Смартфон Apple iPhone 17 Plus 256Gb White",
    price: 109990,
    images: ["/images/phone_mock.png", "/images/phone_mock.png"],
    inStock: true,
  },
  {
    id: "related-5",
    title: "Смартфон Apple iPhone 17 Pro 512Gb Desert Titanium",
    price: 139990,
    images: ["/images/phone_mock.png", "/images/phone_mock.png"],
    inStock: true,
    isNew: true,
  },
];

export const mockProductDetail: ProductDetail = {
  id: "iphone-17-pro",
  title: "Смартфон Apple iPhone 17 Pro 512Gb Cosmic Orange (1 sim + eSIM)",
  price: 129690,
  oldPrice: 146500,
  discount: 5,
  images: [
    "/images/phone_mock.png",
    "/images/phone_mock.png",
    "/images/phone_mock.png",
    "/images/phone_mock.png",
  ],
  inStock: true,
  isSale: true,
  rating: 5.0,
  reviewsCount: 32,
  colors: [
    { id: "orange", name: "Оранжевый", image: "/images/color-orange.png" },
    { id: "blue", name: "Синий", image: "/images/color-blue.png" },
    { id: "silver", name: "Серебристый", image: "/images/color-silver.png" },
  ],
  storageOptions: ["128 GB", "256 GB", "512 GB"],
  selectedStorage: "512 GB",
  selectedColor: "orange",
  category: "Смартфоны Apple iPhone",
  subcategory: "iPhone 17 Pro",
  deliveryInfo: {
    pickup: "г. Москва, улица Барклая, 6Ак1",
    courier: "завтра до 21:00",
  },
  specifications: [
    { label: "Бренд", value: "Apple" },
    { label: "Материал", value: "Алюминий и стекло" },
    { label: "Фронтальная камера", value: "18 МП" },
    { label: "Диагональ экрана", value: "6.3" },
    { label: "Встроенная память", value: "512 Гб" },
    { label: "Оперативная память", value: "12 Гб" },
    { label: "Разрешение экрана", value: "2622 x 1206" },
    { label: "Частота обновления экрана", value: "120 Гц" },
    { label: "Вес", value: "206 г." },
    { label: "Цвет", value: "Оранжевый" },
    { label: "Основная камера", value: "48 МП/48 МП/48 МП" },
    { label: "Тип экрана", value: "Ultra Retina XDR" },
    { label: "Процессор", value: "Apple A19 Pro" },
    { label: "Количество ядер", value: "6" },
    { label: "Емкость аккумулятора", value: "4252 мА⋅ч" },
    { label: "Количество SIM-карт", value: "SIM + eSIM" },
    { label: "Размер", value: "71.9x150х8.75 мм" },
    {
      label: "Комплектация",
      value: "iPhone, кабель USB-C для зарядки, документация",
    },
  ],
};
